import { Router, type IRouter } from "express";
import healthRouter from "./health";
import scenariosRouter from "./scenarios";
import snapshotsRouter from "./snapshots";
import referenceRouter from "./reference";
import advisorRouter from "./advisor";
import observabilityRouter from "./observability";
import assetGenerationRouter from "./asset-generation";
import workspaceAssetsRouter from "./workspace-assets";
import worldGenerationRouter from "./world-generation";
import codingAgentRouter from "./coding-agent";
import networkAccessRouter from "./network-access";
import workspaceAuthRouter from "./workspace-auth";
import workspaceMapsRouter from "./workspace-maps";
import mcpRouter from "./mcp";
import telegramAuthRouter from "./telegram-auth";
import pathPlanningRouter from "./path-planning";
import evolveRouter from "./evolve";
import ragRouter from "./rag";
import sourceDebugRouter from "./source-debug";
import llmHeadsUpRouter from "./llm-heads-up";

const router: IRouter = Router();

router.use(healthRouter);
router.use(scenariosRouter);
router.use(snapshotsRouter);
router.use(referenceRouter);
router.use(observabilityRouter);
router.use(assetGenerationRouter);
router.use(workspaceAssetsRouter);
router.use(worldGenerationRouter);
router.use(codingAgentRouter);
router.use(networkAccessRouter);
router.use(workspaceAuthRouter);
router.use(workspaceMapsRouter);
router.use(mcpRouter);
router.use(telegramAuthRouter);
router.use(pathPlanningRouter);
router.use(evolveRouter);
router.use(ragRouter);
router.use(sourceDebugRouter);
router.use(llmHeadsUpRouter);
router.use(advisorRouter);

export default router;
