import { z } from "zod";

const Id = z.string().min(1).max(160).regex(/^[a-zA-Z0-9._-]+$/);
const Score = z.number().finite().min(0).max(100);

export const SyndicateCommandSchema = z.discriminatedUnion("type", [
  z.object({
    type: z.literal("create_syndicate"),
    commandId: Id,
    tick: z.number().int().nonnegative(),
    syndicateId: Id,
    name: z.string().min(1).max(160),
    leaderNpcId: Id,
  }),
  z.object({
    type: z.literal("recruit_member"),
    commandId: Id,
    tick: z.number().int().nonnegative(),
    syndicateId: Id,
    npcId: Id,
    roleId: Id,
    salary: z.number().finite().nonnegative().max(10_000_000),
    loyalty: Score.default(50),
    ambition: Score.default(50),
    fear: Score.default(20),
    trust: Score.default(50),
    satisfaction: Score.default(50),
    ideologicalAlignment: Score.default(50),
    heart: Score.default(50),
    competence: Score.default(50),
  }),
  z.object({
    type: z.literal("assign_role"),
    commandId: Id,
    tick: z.number().int().nonnegative(),
    syndicateId: Id,
    npcId: Id,
    roleId: Id,
    reason: z.string().min(1).max(500),
  }),
  z.object({
    type: z.literal("influence_territory"),
    commandId: Id,
    tick: z.number().int().nonnegative(),
    syndicateId: Id,
    territoryId: Id,
    approach: z.enum(["community_presence", "commerce", "diplomacy", "information", "defensive_presence"]),
    resourceSpend: z.object({
      capital: z.number().finite().nonnegative().max(10_000_000).default(0),
      supplies: z.number().finite().nonnegative().max(1_000_000).default(0),
      workforce: z.number().finite().nonnegative().max(100_000).default(0),
      intelligence: z.number().finite().nonnegative().max(100_000).default(0),
      influence: z.number().finite().nonnegative().max(100_000).default(0),
    }),
  }),
  z.object({
    type: z.literal("establish_business"),
    commandId: Id,
    tick: z.number().int().nonnegative(),
    syndicateId: Id,
    businessId: Id,
    territoryId: Id,
    category: z.enum(["retail", "transport", "security", "entertainment", "construction", "logistics", "hospitality", "technology", "real_estate", "media"]),
    name: z.string().min(1).max(160),
    managerNpcId: Id.optional(),
  }),
  z.object({
    type: z.literal("set_relationship"),
    commandId: Id,
    tick: z.number().int().nonnegative(),
    syndicateId: Id,
    targetFactionId: Id,
    trustDelta: z.number().finite().min(-25).max(25).default(0),
    respectDelta: z.number().finite().min(-25).max(25).default(0),
    fearDelta: z.number().finite().min(-25).max(25).default(0),
    hostilityDelta: z.number().finite().min(-25).max(25).default(0),
    dependencyDelta: z.number().finite().min(-25).max(25).default(0),
    reason: z.string().min(1).max(500),
  }),
  z.object({
    type: z.literal("resolve_internal_politics"),
    commandId: Id,
    tick: z.number().int().nonnegative(),
    syndicateId: Id,
  }),
  z.object({
    type: z.literal("choose_strategy"),
    commandId: Id,
    tick: z.number().int().nonnegative(),
    syndicateId: Id,
    strategy: z.enum(["economic_expansion", "territorial_consolidation", "recruitment", "diplomacy", "public_legitimacy", "intelligence_gathering", "internal_stability", "defensive_preparation"]),
    reason: z.string().min(1).max(500),
  }),
  z.object({
    type: z.literal("advance_tick"),
    commandId: Id,
    tick: z.number().int().nonnegative(),
    ticks: z.number().int().min(1).max(168).default(1),
  }),
  z.object({
    type: z.literal("update_world_from_rag"),
    commandId: Id,
    tick: z.number().int().nonnegative(),
    ragRevision: z.string().min(1).max(256),
    npcIds: z.array(Id).max(10_000).default([]),
  }),
]);

export type SyndicateCommand = z.infer<typeof SyndicateCommandSchema>;
