#!/usr/bin/env python3
"""Forward proxy used as the coding-agent worker's only egress path.

Deploy the worker on an internal-only network. This proxy is the sole dual-homed
service. Provider API transport is separated from tool/browser egress. Tool egress
is denied, explicitly allowlisted, or temporarily Ultra-approved by a run-bound
policy generated by the API server.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import ipaddress
import json
import os
import select
import socket
import socketserver
import ssl
import time
import urllib.parse
from pathlib import Path
from typing import Any

HOST = os.getenv("NETWORK_GATE_HOST", "0.0.0.0")
PORT = int(os.getenv("NETWORK_GATE_PORT", "8888"))
POLICY_ROOT = Path(os.getenv("NETWORK_GATE_POLICY_ROOT", "/network-policies")).resolve()
AUDIT_ROOT = POLICY_ROOT / "audit"
PENDING_ROOT = POLICY_ROOT / "pending"
INFRA_TOKEN = os.getenv("NETWORK_GATE_INFRA_TOKEN", "")
MODEL_DOMAINS = {
    value.strip().lower()
    for value in os.getenv(
        "NETWORK_GATE_MODEL_DOMAINS",
        "openrouter.ai,api.openai.com,api.anthropic.com,api.deepseek.com,generativelanguage.googleapis.com",
    ).split(",")
    if value.strip()
}
INFRA_DOMAINS = {
    value.strip().lower()
    for value in os.getenv(
        "NETWORK_GATE_INFRA_DOMAINS",
        "github.com,api.github.com,objects.githubusercontent.com,raw.githubusercontent.com,codeload.github.com",
    ).split(",")
    if value.strip()
}
MAX_HEADER_BYTES = 64 * 1024
CONNECT_TIMEOUT = 20
IDLE_TIMEOUT = 120
ALLOWED_CAPABILITIES = {
    "web_search",
    "web_fetch",
    "package_registry",
    "source_docs",
    "issue_tracker",
}
SEARCH_DOMAINS = {
    "www.google.com",
    "google.com",
    "www.bing.com",
    "bing.com",
    "search.brave.com",
    "duckduckgo.com",
    "html.duckduckgo.com",
}
PACKAGE_DOMAINS = {
    "registry.npmjs.org",
    "registry.yarnpkg.com",
    "pypi.org",
    "files.pythonhosted.org",
    "crates.io",
    "index.crates.io",
    "rubygems.org",
    "repo.maven.apache.org",
}
ISSUE_DOMAINS = {
    "github.com",
    "api.github.com",
    "gitlab.com",
    "api.gitlab.com",
}


class ThreadingProxy(socketserver.ThreadingMixIn, socketserver.TCPServer):
    allow_reuse_address = True
    daemon_threads = True


class ProxyHandler(socketserver.StreamRequestHandler):
    def handle(self) -> None:
        self.connection.settimeout(IDLE_TIMEOUT)
        identity = "unknown"
        policy: dict[str, Any] = {}
        host = "unknown"
        capability = "web_fetch"
        method = "UNKNOWN"
        scheme = "https"
        path = "/"
        try:
            request_line = self.rfile.readline(MAX_HEADER_BYTES).decode("iso-8859-1").strip()
            if not request_line:
                return
            parts = request_line.split(" ", 2)
            if len(parts) != 3:
                return self.error(400, "Malformed proxy request")
            method, target, version = parts
            headers = read_headers(self.rfile)
            identity, policy = authenticate(headers.get("proxy-authorization", ""))
            host, port, scheme, path = parse_target(method, target, headers)
            capability = classify_capability(host)
            category, allowed, reason = authorize(identity, policy, host, port, scheme, capability)

            if category == "tool":
                record_request(identity, policy, method, scheme, host, port, path, capability, allowed, reason)
            if not allowed:
                if category == "tool":
                    record_pending(identity, policy, host, capability, reason)
                return self.error(403, f"Network access denied for {host}: {reason}")

            try:
                addresses = safe_addresses(host, port)
            except (OSError, ValueError) as error:
                if category == "tool":
                    record_request(identity, policy, method, scheme, host, port, path, capability, False, f"address blocked: {error}")
                raise

            if method.upper() == "CONNECT":
                return self.tunnel(addresses, host, port)
            return self.forward(method, version, scheme, path, host, port, headers, addresses)
        except (ConnectionError, OSError, ValueError, TimeoutError) as error:
            try:
                self.error(502, f"Proxy connection failed: {type(error).__name__}")
            except OSError:
                pass

    def tunnel(self, addresses: list[tuple[Any, ...]], host: str, port: int) -> None:
        upstream = connect_any(addresses, CONNECT_TIMEOUT)
        try:
            self.wfile.write(b"HTTP/1.1 200 Connection Established\r\nProxy-Agent: T1-Network-Gate\r\n\r\n")
            self.wfile.flush()
            relay(self.connection, upstream)
        finally:
            upstream.close()

    def forward(
        self,
        method: str,
        version: str,
        scheme: str,
        path: str,
        host: str,
        port: int,
        headers: dict[str, str],
        addresses: list[tuple[Any, ...]],
    ) -> None:
        upstream = connect_any(addresses, CONNECT_TIMEOUT)
        try:
            if scheme == "https":
                context = ssl.create_default_context()
                upstream = context.wrap_socket(upstream, server_hostname=host)
            outgoing = [f"{method} {path} {version}\r\n"]
            for name, value in headers.items():
                if name in {"proxy-authorization", "proxy-connection", "connection"}:
                    continue
                outgoing.append(f"{canonical_header(name)}: {value}\r\n")
            outgoing.append("Connection: close\r\n\r\n")
            upstream.sendall("".join(outgoing).encode("iso-8859-1"))
            content_length = int(headers.get("content-length", "0") or 0)
            remaining = content_length
            while remaining > 0:
                chunk = self.rfile.read(min(64 * 1024, remaining))
                if not chunk:
                    break
                upstream.sendall(chunk)
                remaining -= len(chunk)
            while True:
                chunk = upstream.recv(64 * 1024)
                if not chunk:
                    break
                self.connection.sendall(chunk)
        finally:
            upstream.close()

    def error(self, status: int, message: str) -> None:
        body = json.dumps({"error": message}).encode("utf-8")
        response = (
            f"HTTP/1.1 {status} {status_text(status)}\r\n"
            "Content-Type: application/json\r\n"
            f"Content-Length: {len(body)}\r\n"
            "Connection: close\r\n\r\n"
        ).encode("ascii") + body
        self.connection.sendall(response)


def read_headers(stream: Any) -> dict[str, str]:
    headers: dict[str, str] = {}
    total = 0
    while True:
        line = stream.readline(MAX_HEADER_BYTES)
        total += len(line)
        if total > MAX_HEADER_BYTES:
            raise ValueError("Headers too large")
        if line in {b"\r\n", b"\n", b""}:
            break
        text = line.decode("iso-8859-1").rstrip("\r\n")
        if ":" not in text:
            raise ValueError("Malformed header")
        name, value = text.split(":", 1)
        headers[name.strip().lower()] = value.strip()
    return headers


def authenticate(header: str) -> tuple[str, dict[str, Any]]:
    if not header.lower().startswith("basic "):
        raise ValueError("Proxy authentication required")
    try:
        decoded = base64.b64decode(header.split(" ", 1)[1]).decode("utf-8")
        identity, supplied = decoded.split(":", 1)
    except (ValueError, UnicodeDecodeError) as error:
        raise ValueError("Invalid proxy authentication") from error

    if identity == "infrastructure":
        if len(INFRA_TOKEN) < 24 or not secrets_equal(supplied, INFRA_TOKEN):
            raise ValueError("Invalid infrastructure proxy credential")
        return identity, {
            "mode": "infrastructure",
            "allowedHosts": sorted(INFRA_DOMAINS),
            "allowedCapabilities": [],
        }

    safe_identity = safe_id(identity)
    policy_path = POLICY_ROOT / f"{safe_identity}.json"
    try:
        policy = json.loads(policy_path.read_text(encoding="utf-8"))
    except (FileNotFoundError, json.JSONDecodeError) as error:
        raise ValueError("Unknown network policy") from error
    if not isinstance(policy, dict) or not secrets_equal(str(policy.get("nonce", "")), supplied):
        raise ValueError("Invalid run proxy credential")
    expires_at = float(policy.get("expiresAtEpoch", 0))
    if expires_at <= time.time():
        raise ValueError("Network policy expired")
    validate_policy(policy)
    return safe_identity, policy


def validate_policy(policy: dict[str, Any]) -> None:
    mode = str(policy.get("mode", "deny"))
    if mode not in {"deny", "allowlisted", "ultra"}:
        raise ValueError("Unknown network authorization mode")
    hosts = policy.get("allowedHosts", [])
    capabilities = policy.get("allowedCapabilities", [])
    if not isinstance(hosts, list) or not all(isinstance(value, str) for value in hosts):
        raise ValueError("allowedHosts must be a string array")
    if not isinstance(capabilities, list) or not all(value in ALLOWED_CAPABILITIES for value in capabilities):
        raise ValueError("allowedCapabilities contains an unsupported value")
    if policy.get("requireHttps") is not True:
        raise ValueError("HTTPS enforcement is required")
    if policy.get("blockPrivateNetworks") is not True:
        raise ValueError("Private-network blocking is required")
    if policy.get("rejectRedirectsUntilRevalidated") is not True:
        raise ValueError("Redirect revalidation is required")


def parse_target(method: str, target: str, headers: dict[str, str]) -> tuple[str, int, str, str]:
    if method.upper() == "CONNECT":
        host, port = split_host_port(target, 443)
        return host, port, "https", "/"
    parsed = urllib.parse.urlsplit(target)
    if parsed.scheme not in {"http", "https"}:
        host_header = headers.get("host", "")
        host, port = split_host_port(host_header, 80)
        return host, port, "http", target or "/"
    if not parsed.hostname:
        raise ValueError("Proxy URL is missing a host")
    port = parsed.port or (443 if parsed.scheme == "https" else 80)
    path = urllib.parse.urlunsplit(("", "", parsed.path or "/", parsed.query, ""))
    return normalize_domain(parsed.hostname), port, parsed.scheme, path


def split_host_port(value: str, default_port: int) -> tuple[str, int]:
    if value.startswith("["):
        parsed = urllib.parse.urlsplit(f"scheme://{value}")
        if not parsed.hostname:
            raise ValueError("Invalid host")
        return normalize_domain(parsed.hostname), parsed.port or default_port
    host, separator, port_text = value.rpartition(":")
    if separator and port_text.isdigit():
        return normalize_domain(host), int(port_text)
    return normalize_domain(value), default_port


def authorize(
    identity: str,
    policy: dict[str, Any],
    host: str,
    port: int,
    scheme: str,
    capability: str,
) -> tuple[str, bool, str]:
    if identity == "infrastructure":
        allowed = matches_any(host, set(policy.get("allowedHosts", [])))
        return "infrastructure", allowed, "infrastructure allowlist" if allowed else "infrastructure host not allowlisted"

    model_hosts = {
        normalize_domain(str(value))
        for value in policy.get("modelProviderDomains", [])
        if value
    } | MODEL_DOMAINS
    if matches_any(host, model_hosts):
        if scheme != "https" or port != 443:
            return "model", False, "model transport requires HTTPS on port 443"
        return "model", True, "model-provider transport"

    if scheme != "https" or port != 443:
        return "tool", False, "tool egress requires HTTPS on port 443"

    mode = str(policy.get("mode", "deny"))
    allowed_hosts = {
        normalize_domain(str(value))
        for value in policy.get("allowedHosts", [])
        if value
    }
    allowed_capabilities = {
        str(value)
        for value in policy.get("allowedCapabilities", [])
        if str(value) in ALLOWED_CAPABILITIES
    }
    if mode == "ultra":
        return "tool", True, "explicit Ultra approval"
    if mode == "allowlisted":
        if not matches_any(host, allowed_hosts):
            return "tool", False, "host was not approved for this run"
        if capability not in allowed_capabilities:
            return "tool", False, f"capability {capability} was not approved for this run"
        return "tool", True, "run-bound Ask First approval"
    return "tool", False, "Ask First deny-all policy"


def classify_capability(host: str) -> str:
    normalized = normalize_domain(host)
    if matches_any(normalized, SEARCH_DOMAINS):
        return "web_search"
    if matches_any(normalized, PACKAGE_DOMAINS):
        return "package_registry"
    if matches_any(normalized, ISSUE_DOMAINS):
        return "issue_tracker"
    if normalized.startswith("docs.") or normalized.startswith("developer.") or normalized.endswith("readthedocs.io") or normalized == "docs.rs":
        return "source_docs"
    return "web_fetch"


def safe_addresses(host: str, port: int) -> list[tuple[Any, ...]]:
    addresses = socket.getaddrinfo(host, port, type=socket.SOCK_STREAM)
    if not addresses:
        raise ValueError("Target did not resolve")
    unsafe: list[str] = []
    safe: list[tuple[Any, ...]] = []
    for address in addresses:
        ip = ipaddress.ip_address(address[4][0])
        if ip.is_private or ip.is_loopback or ip.is_link_local or ip.is_multicast or ip.is_reserved or ip.is_unspecified:
            unsafe.append(str(ip))
        else:
            safe.append(address)
    if unsafe:
        raise ValueError("Target resolved to blocked private or special-use addresses")
    if not safe:
        raise ValueError("Target has no usable public address")
    return safe


def connect_any(addresses: list[tuple[Any, ...]], timeout: int) -> socket.socket:
    last_error: OSError | None = None
    for family, socktype, proto, _, sockaddr in addresses:
        sock = socket.socket(family, socktype, proto)
        sock.settimeout(timeout)
        try:
            sock.connect(sockaddr)
            sock.settimeout(None)
            return sock
        except OSError as error:
            last_error = error
            sock.close()
    raise last_error or OSError("No usable target address")


def relay(client: socket.socket, upstream: socket.socket) -> None:
    sockets = [client, upstream]
    while True:
        readable, _, exceptional = select.select(sockets, [], sockets, IDLE_TIMEOUT)
        if exceptional or not readable:
            return
        for source in readable:
            data = source.recv(64 * 1024)
            if not data:
                return
            destination = upstream if source is client else client
            destination.sendall(data)


def record_request(
    identity: str,
    policy: dict[str, Any],
    method: str,
    scheme: str,
    host: str,
    port: int,
    path: str,
    capability: str,
    allowed: bool,
    reason: str,
) -> None:
    AUDIT_ROOT.mkdir(parents=True, exist_ok=True)
    timestamp = time.time_ns()
    digest = hashlib.sha256(f"{identity}:{timestamp}:{host}:{path}".encode()).hexdigest()[:16]
    payload = {
        "at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "runId": identity,
        "capability": capability,
        "method": method.upper() if method.upper() in {"GET", "HEAD", "POST", "PUT", "PATCH", "DELETE"} else "GET",
        "origin": f"https://{host}" if port == 443 else f"{scheme}://{host}:{port}",
        "path": path[:1000] or "/",
        "allowed": bool(allowed),
        "reason": reason[:2000],
        "mode": policy.get("mode", "deny"),
    }
    atomic_write_json(AUDIT_ROOT / f"{safe_id(identity)}-{timestamp}-{digest}.json", payload)


def record_pending(identity: str, policy: dict[str, Any], host: str, capability: str, reason: str) -> None:
    PENDING_ROOT.mkdir(parents=True, exist_ok=True)
    digest = hashlib.sha256(f"{identity}:{host}:{capability}".encode()).hexdigest()[:20]
    payload = {
        "id": digest,
        "runId": identity,
        "domain": host,
        "capability": capability,
        "reason": reason,
        "mode": policy.get("mode", "deny"),
        "requestedAt": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    atomic_write_json(PENDING_ROOT / f"{safe_id(identity)}-{digest}.json", payload)


def atomic_write_json(path: Path, payload: dict[str, Any]) -> None:
    temporary = path.with_suffix(f".{time.time_ns()}.tmp")
    temporary.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    temporary.chmod(0o600)
    os.replace(temporary, path)


def normalize_domain(value: str) -> str:
    domain = value.strip().lower().rstrip(".")
    if not domain or len(domain) > 253 or "/" in domain or "@" in domain or "*" in domain:
        raise ValueError("Invalid domain")
    return domain.encode("idna").decode("ascii")


def matches_any(host: str, domains: set[str]) -> bool:
    normalized = normalize_domain(host)
    return any(normalized == domain or normalized.endswith(f".{domain}") for domain in domains)


def safe_id(value: str) -> str:
    safe = "".join(character if character.isalnum() or character in "._-" else "-" for character in value)[:180]
    if not safe or safe in {".", ".."}:
        raise ValueError("Invalid policy identity")
    return safe


def canonical_header(value: str) -> str:
    return "-".join(part.capitalize() for part in value.split("-"))


def secrets_equal(first: str, second: str) -> bool:
    return hmac.compare_digest(first.encode(), second.encode())


def status_text(status: int) -> str:
    return {
        400: "Bad Request",
        403: "Forbidden",
        407: "Proxy Authentication Required",
        502: "Bad Gateway",
    }.get(status, "Error")


def main() -> None:
    POLICY_ROOT.mkdir(parents=True, exist_ok=True)
    AUDIT_ROOT.mkdir(parents=True, exist_ok=True)
    PENDING_ROOT.mkdir(parents=True, exist_ok=True)
    with ThreadingProxy((HOST, PORT), ProxyHandler) as server:
        print(json.dumps({"event": "network-gate.started", "host": HOST, "port": PORT}), flush=True)
        server.serve_forever(poll_interval=0.5)


if __name__ == "__main__":
    main()
