import { ChevronLeft, ShieldAlert } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { useApp } from "../context/AppContext";

const theories = ["Rational choice", "Strain", "Routine activity", "Social learning", "Labeling", "Situational crime prevention"];
export function CaseBoardPage() {
  const { id = "" } = useParams(); const { project } = useApp(); const current = project(id);
  if (!current) return <div className="page">Projekt ikke fundet.</div>;
  return <div className="page container"><Link className="icon-text" to={`/project/${id}`}><ChevronLeft size={17} />Tilbage</Link><header className="page-heading"><h1>Case board</h1><p>Personer, spor, relationer og kriminologiske perspektiver.</p></header><div className="two-grid"><section className="panel content-card"><span className="eyebrow">PERSONER</span>{current.characters.map((character) => <article className="list-card" key={character.id}><div className="row-between"><strong>{character.name}</strong><span className="tag">{character.role}</span></div><p>{character.bio}</p><small>Motiv: {character.motive}</small></article>)}</section><section className="panel content-card"><span className="eyebrow">BEVISER</span>{current.evidence.map((evidence) => <article className="list-card" key={evidence.id}><div className="row-between"><strong>{evidence.name}</strong><span className={`tag ${evidence.reliability === "red_herring" ? "danger" : ""}`}>{evidence.reliability.replace("_", " ")}</span></div><p>{evidence.notes}</p></article>)}</section><section className="panel content-card"><span className="eyebrow">RELATIONER</span>{current.relationships.map((relation) => { const from = current.characters.find((c) => c.id === relation.fromId)?.name; const to = current.characters.find((c) => c.id === relation.toId)?.name; return <div className="relation" key={relation.id}><strong>{from}</strong><span>— {relation.label} →</span><strong>{to}</strong></div>; })}</section><section className="panel content-card"><span className="eyebrow">TEORILAG</span><div className="tag-row">{theories.map((theory) => <span className="tag" key={theory}>{theory}</span>)}</div></section><section className="panel content-card wide"><span className="eyebrow"><ShieldAlert size={15} /> ETIK</span><div className="check-grid">{["Har ofrene værdighed og indre liv?", "Undgås stereotyper?", "Er virkelige kilder anonymiseret?", "Undgår teksten operationelle instruktioner?"].map((question) => <label key={question}><input type="checkbox" />{question}</label>)}</div></section></div></div>;
}
