import { ChevronLeft, Headphones } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { useApp } from "../context/AppContext";
import { useTts } from "../context/TtsContext";
export function PreviewsPage() {
  const { id = "" } = useParams(); const { project } = useApp(); const current = project(id); const tts = useTts();
  if (!current) return <div className="page">Projekt ikke fundet.</div>;
  return <div className="page narrow"><Link className="icon-text" to={`/project/${id}`}><ChevronLeft size={17} />Tilbage</Link><header className="page-heading"><h1>AI Preview Reports</h1><p>Gemte analyser af manuskriptets udvikling.</p></header>{current.previews.length === 0 ? <section className="panel empty">Ingen previews endnu.</section> : current.previews.map((snapshot) => { const report = snapshot.report; const text = [report.synopsis, report.tone, report.plot, report.pacing, report.characters, ...report.continuity, report.clues, report.criminology, ...report.nextSteps, report.nextSceneSuggestion].join("\n\n"); return <article className="panel report" key={snapshot.id}><div className="row-between"><div><span className="eyebrow">{new Date(snapshot.createdAt).toLocaleString("da-DK")}</span><h2>{snapshot.wordCount.toLocaleString("da-DK")} ord</h2></div><button className="button secondary" onClick={() => void tts.startText("AI Preview", text)}><Headphones size={16} />Læs rapport</button></div><ReportSection title="Synopsis" body={report.synopsis} /><div className="two-grid"><ReportSection title="Tone" body={report.tone} /><ReportSection title="Plot" body={report.plot} /><ReportSection title="Pacing" body={report.pacing} /><ReportSection title="Karakterer" body={report.characters} /><ReportSection title="Spor" body={report.clues} /><ReportSection title="Kriminologi" body={report.criminology} /></div><ReportSection title="Kontinuitet" body={report.continuity.join("\n• ")} /><ReportSection title="Næste skridt" body={report.nextSteps.map((item, i) => `${i + 1}. ${item}`).join("\n")} /><ReportSection title="Næste scene" body={report.nextSceneSuggestion} /></article>; })}</div>;
}
function ReportSection({ title, body }: { title: string; body: string }) { return <section className="report-section"><span className="eyebrow">{title}</span><p>{body}</p></section>; }
