import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Download, ExternalLink, Github, KeyRound, Loader2, Save, ShieldCheck, Trash2, Volume2 } from "lucide-react";
import { useApp } from "../context/AppContext";
import { apiJson, secretsApi, type SecretStatus } from "../lib/api";
import type { ProviderId } from "../types";

const tabs = ["AI Providers", "Model Routing", "Text to Speech", "GitHub & Backup", "Data & Privacy", "App"] as const;
type Tab = typeof tabs[number];
const providers: Array<{ id: ProviderId; name: string; hint: string }> = [
  { id: "openrouter", name: "OpenRouter", hint: "sk-or-v1-…" },
  { id: "openai", name: "OpenAI", hint: "sk-…" },
  { id: "anthropic", name: "Anthropic", hint: "sk-ant-…" },
  { id: "gemini", name: "Google Gemini", hint: "AIza…" },
  { id: "groq", name: "Groq", hint: "gsk_…" },
  { id: "mistral", name: "Mistral", hint: "API key" },
  { id: "elevenlabs", name: "ElevenLabs", hint: "API key" },
  { id: "github", name: "GitHub token", hint: "github_pat_…" },
  { id: "custom", name: "Custom OpenAI-compatible", hint: "API key" }
];

export function SettingsPage() {
  const { state, setState, exportAll, reset } = useApp();
  const [tab, setTab] = useState<Tab>("AI Providers");
  const [statuses, setStatuses] = useState<SecretStatus[]>([]);
  const [secure, setSecure] = useState(false);
  const refresh = () => secretsApi.list().then((result) => { setStatuses(result.statuses); setSecure(result.secureStorage); }).catch(() => { setStatuses([]); setSecure(false); });
  useEffect(() => { void refresh(); }, []);
  return <div className="page container"><header className="page-heading"><h1>Indstillinger</h1><p>AI, secrets, oplæsning, GitHub og data.</p></header><div className="settings-layout"><nav className="settings-tabs">{tabs.map((item) => <button className={tab === item ? "active" : ""} key={item} onClick={() => setTab(item)}>{item}</button>)}</nav><main className="settings-content">{tab === "AI Providers" && <ProvidersPanel statuses={statuses} secure={secure} refresh={refresh} />}{tab === "Model Routing" && <RoutingPanel />}{tab === "Text to Speech" && <TtsPanel />}{tab === "GitHub & Backup" && <GithubPanel />}{tab === "Data & Privacy" && <section className="panel settings-panel"><h2>Dine data</h2><p>Historierne gemmes lokalt i browseren i denne MVP. API-secrets gemmes krypteret på serveren.</p><div className="button-row"><button className="button secondary" onClick={exportAll}><Download size={16} />Eksportér JSON</button><button className="button danger" onClick={() => { if (confirm("Slet alle lokale CaseCraft-data?")) reset(); }}><Trash2 size={16} />Slet lokale data</button></div></section>}{tab === "App" && <section className="panel settings-panel"><h2>App</h2><p>Designet er mobil-first og installérbart som PWA. Brug Firefox-menuen → “Installér” eller “Føj til startskærm”.</p><label className="field">Dagligt ordmål<input type="number" value={state.goals.dailyWordGoal} onChange={(event) => setState((current) => ({ ...current, goals: { ...current.goals, dailyWordGoal: Number(event.target.value) || 0 } }))} /></label></section>}</main></div></div>;
}

function ProvidersPanel({ statuses, secure, refresh }: { statuses: SecretStatus[]; secure: boolean; refresh: () => void }) {
  return <section className="panel settings-panel"><div className="row-between"><div><h2><KeyRound size={19} />AI Providers</h2><p>Secrets sendes til backend og returneres aldrig til browseren.</p></div><span className={secure ? "status ok" : "status warning"}>{secure ? <ShieldCheck size={15} /> : null}{secure ? "Krypteret storage aktiv" : "Backend ikke tilgængelig"}</span></div><div className="provider-list">{providers.map((provider) => <ProviderRow key={provider.id} provider={provider} status={statuses.find((item) => item.provider === provider.id)} refresh={refresh} />)}</div></section>;
}
function ProviderRow({ provider, status, refresh }: { provider: { id: ProviderId; name: string; hint: string }; status?: SecretStatus; refresh: () => void }) {
  const [key, setKey] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const act = async (action: "save" | "test" | "remove") => { setBusy(true); setMessage(""); try { if (action === "save") await secretsApi.save(provider.id, key); if (action === "test") { const result = await secretsApi.test(provider.id); setMessage(result.message); } if (action === "remove") await secretsApi.remove(provider.id); setKey(""); refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Fejl"); } finally { setBusy(false); } };
  return <div className="provider-row"><div className="provider-title"><strong>{provider.name}</strong><span className={status?.configured ? "status ok" : "status"}>{status?.configured ? `Forbundet · ••••${status.last4}` : "Ikke konfigureret"}</span></div><input type="password" value={key} onChange={(event) => setKey(event.target.value)} placeholder={status?.configured ? "Indsæt ny nøgle for at udskifte" : provider.hint} autoComplete="off" /><div className="provider-actions"><button disabled={busy || !key.trim()} onClick={() => void act("save")}><Save size={14} />Gem</button><button disabled={busy || !status?.configured} onClick={() => void act("test")}>{busy ? <Loader2 className="spin" size={14} /> : <CheckCircle2 size={14} />}Test</button><button disabled={busy || !status?.configured} onClick={() => void act("remove")}><Trash2 size={14} />Slet</button></div>{message && <small>{message}</small>}</div>;
}
function RoutingPanel() {
  const { state, setState } = useApp(); const [models, setModels] = useState<Array<{ id: string; name: string; free: boolean; context: number }>>([]);
  useEffect(() => { apiJson<{ models: typeof models }>(`/api/models/openrouter?free=${state.ai.onlyFree}`).then((result) => setModels(result.models)).catch(() => setModels([{ id: "openrouter/auto", name: "OpenRouter Auto", free: false, context: 0 }, { id: "meta-llama/llama-3.1-8b-instruct:free", name: "Llama 3.1 8B Free", free: true, context: 131072 }])); }, [state.ai.onlyFree]);
  const setAi = (patch: Partial<typeof state.ai>) => setState((current) => ({ ...current, ai: { ...current.ai, ...patch } }));
  return <section className="panel settings-panel"><h2>Model Routing</h2><label className="switch-row"><span>Kun gratis OpenRouter-modeller</span><input type="checkbox" checked={state.ai.onlyFree} onChange={(event) => setAi({ onlyFree: event.target.checked })} /></label><div className="settings-grid">{([['Chat','chatModel'],['Rewrite','rewriteModel'],['Hel-manuskriptanalyse','analysisModel'],['Research','researchModel']] as const).map(([label,key]) => <label className="field" key={key}>{label}<select value={state.ai[key]} onChange={(event) => setAi({ [key]: event.target.value })}><option value="openrouter/auto">Auto</option>{models.map((model) => <option key={model.id} value={model.id}>{model.name}{model.free ? " · gratis" : ""}</option>)}</select></label>)}</div><label className="field">Custom Base URL<input value={state.ai.customBaseUrl} onChange={(event) => setAi({ customBaseUrl: event.target.value })} placeholder="https://server.example/v1" /></label></section>;
}
function TtsPanel() {
  const { state, setState } = useApp(); const setTts = (patch: Partial<typeof state.tts>) => setState((current) => ({ ...current, tts: { ...current.tts, ...patch } }));
  return <section className="panel settings-panel"><h2><Volume2 size={19} />Text to Speech</h2><p>OpenAI, ElevenLabs og custom provider bruger genereret lyd i den globale HTMLAudio-player. Browser-mode er kun fallback og kan stoppe i baggrunden.</p><div className="settings-grid"><label className="field">Provider<select value={state.tts.provider} onChange={(event) => setTts({ provider: event.target.value as typeof state.tts.provider })}><option value="browser">Browser fallback</option><option value="openai">OpenAI TTS</option><option value="elevenlabs">ElevenLabs</option><option value="custom">Custom OpenAI-compatible</option></select></label><label className="field">Model<input value={state.tts.model} onChange={(event) => setTts({ model: event.target.value })} /></label><label className="field">Stemme / voice ID<input value={state.tts.voice} onChange={(event) => setTts({ voice: event.target.value })} /></label><label className="field">Format<select value={state.tts.format} onChange={(event) => setTts({ format: event.target.value as typeof state.tts.format })}><option value="mp3">MP3</option><option value="opus">Opus</option><option value="wav">WAV</option></select></label><label className="field">Hastighed<input type="number" min="0.75" max="2" step="0.05" value={state.tts.speed} onChange={(event) => setTts({ speed: Number(event.target.value) })} /></label><label className="field">Maks. tegn pr. segment<input type="number" min="300" max="5000" value={state.tts.maxChunkLength} onChange={(event) => setTts({ maxChunkLength: Number(event.target.value) })} /></label></div><label className="field">Custom TTS Base URL<input value={state.tts.customBaseUrl} onChange={(event) => setTts({ customBaseUrl: event.target.value })} /></label><div className="compat-note"><strong>Firefox Android:</strong> Media Session og et rigtigt audio-element øger chancen for fortsat afspilning ved faneskift. Android kan stadig tvangslukke en fane under aggressiv batteri- eller hukommelsesstyring. Kø og position gendannes, når appen åbnes igen.</div></section>;
}
function GithubPanel() {
  const { state, setState, exportAll } = useApp(); const [status, setStatus] = useState(""); const [busy, setBusy] = useState(false);
  const github = state.github; const setGithub = (patch: Partial<typeof github>) => setState((current) => ({ ...current, github: { ...current.github, ...patch } }));
  const test = async () => { setBusy(true); try { const result = await apiJson<{ ok: boolean; message: string }>(`/api/github/status?owner=${encodeURIComponent(github.owner)}&repo=${encodeURIComponent(github.repo)}`); setStatus(result.message); } catch (error) { setStatus(error instanceof Error ? error.message : "Kræver GitHub-token"); } finally { setBusy(false); } };
  const repoUrl = useMemo(() => github.owner && github.repo ? `https://github.com/${github.owner}/${github.repo}` : "", [github]);
  return <section className="panel settings-panel"><h2><Github size={19} />GitHub & Backup</h2><p>GitHub skal være source of truth. Gem et GitHub-token under AI Providers, og opret/tilslut repository fra Devin eller GitHub.</p><div className="settings-grid"><label className="field">Owner<input value={github.owner} onChange={(event) => setGithub({ owner: event.target.value })} /></label><label className="field">Repository<input value={github.repo} onChange={(event) => setGithub({ repo: event.target.value })} /></label><label className="field">Branch<input value={github.branch} onChange={(event) => setGithub({ branch: event.target.value || "main" })} /></label></div><div className="button-row"><button className="button primary" disabled={busy || !github.owner || !github.repo} onClick={() => void test()}>{busy ? <Loader2 className="spin" size={16} /> : <Github size={16} />}Test repository</button>{repoUrl && <a className="button secondary" target="_blank" rel="noreferrer" href={repoUrl}><ExternalLink size={16} />Open repository</a>}<button className="button secondary" onClick={exportAll}><Download size={16} />Eksportér data</button></div><p className="status-line">{status || "Status: kræver GitHub-forbindelse/token. Ingen mock-success vises."}</p><div className="compat-note">Source ZIP og BAT-launchers ligger i repository-root. Følg START_HERE.md og DEVELOP_WITH_DEVIN.md.</div></section>;
}
